#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.

cdnPath="$HOME/Repos/fdp-devops/code/cdn"

if [ -d "$cdnPath/designs/$1" ]; then
  cd "$cdnPath/designs/$1"
elif [ -d "$cdnPath/designs/np_$1" ]; then
  cd "$cdnPath/designs/np_$1"
elif [ -d "$cdnPath/designs/pp_$1" ]; then
  cd "$cdnPath/designs/pp_$1"
else
  find "$cdnPath/" -iname "$1"
fi
