#!/usr/bin/env bash
#
# Run all dotfiles updaters.

set -e

cd "$(dirname $0)"/..

# find the updaters and run them iteratively
find . -name update.sh | while read updater ; do sh -c "${updater}" ; done
